### ISSUE TITLE
sorce code directory question

### ISSUE THREAD

**Issue by meshpaul** [nuhkoca/kotlin-modular-tdd-coroutines-mvvm#1]
Hi should sorce code directory be kotlin/kt not java unless you plan to store java code?

**Comment by nuhkoca** [comment]
Hi @meshpaul ,

Thanks for the issue. In fact, custom `sourceSet dir` isn't supported by Android Studio as far as I know. However, there is a trick which might handle this in 

> build.gradle

```
sourceSets {
        getByName("main").java.srcDirs("src/main/kotlin")
    }
```
